DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]


OPTIM:
  NAME: "sgd"
  LR: 0.032 
  MAX_EPOCH: 120
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  #WEIGHT_DECAY: 0.01

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  XCoOp:
    ENABLE: True
    ENABLE_W: False
    N_CTX: 4 
    CTX_INIT: "a photo of a"
    CLINICAL_PROMPTS: [
      "a photo of a {}, clear lung fields, normal mediastinal silhouette.",  # normal
      "a photo of a {}, alveolar consolidation, air bronchograms, pleural effusion, obscured cardiac or diaphragmatic borders.", # pneumonia
    ]
    PREC: "amp" 
    XCoOp_LOSS_WEIGHT: 5.0 
    XCoOp_TOKEN_LOSS_WEIGHT: 5.0
    VISUAL_FEATURE_NUMBER: 2
    TEXT_PROMPT_NUMBER: 4

TEST:
  FINAL_MODEL: best_val

